travis ciでci/cdの設定を行う
hgaiji/EDAR pull request #11
Opened 2021-01-14 14:29 UTC by hgaiji

# 実装内容
### ci (githubにpushされるたびにチェックする)
- 文法チェック
  - `yarn eslint . --ext .tsx --ext .ts`
- テストコード実行
  -  `yarn test`
### cd (masterブランチにmergeされた時に実行)
- firebaseにreactアプリをdeploy

2021-01-19 15:56 UTC, hgaiji commented
travis ciでは、Travis CI社が運営するサーバー上(ubuntuなど)で実行することができる。(どの環境で実行するかは`.travis.yaml`で設定することができる→今回はubuntuを選択した。)
今回はこのubuntu上でdocker環境を用いて、ci/cdを設定するようにした。

2021-01-23 04:48 UTC, Yuki-TU reviewed
プルリクエストする際に、各ファイルがどういった役割を果たしているのかを記述してください。

2021-01-23 04:54 UTC, hgaiji commented
> プルリクエストする際に、各ファイルがどういった役割を果たしているのかを記述してください。

こちら対応しました。
https://github.com/hgaiji/EDAR/pull/11#issue-554968856

2021-01-23 06:16 UTC, Yuki-TU requested changes

2021-01-23 06:16 UTC, Yuki-TU commented on .travis.yml
> +        - docker run -it -e CI=true --entrypoint=bash $DOCKER_IMAGE_NAME -c "yarn eslint . --ext .tsx --ext .ts"
`yarn eslint . --ext .tsx --ext .ts`は正常終了する（終了時コマンド入力を求められない）ため、引数`-e CI=true`は不要かと思います。

2021-01-23 06:27 UTC, Yuki-TU requested changes

2021-01-23 06:27 UTC, Yuki-TU commented on .travis.yml
> +      if: branch = master
`master`ではなくて、`main`ではないでしょうか。

2021-01-23 06:47 UTC, hgaiji commented on .travis.yml
> +        - docker run -it -e CI=true --entrypoint=bash $DOCKER_IMAGE_NAME -c "yarn eslint . --ext .tsx --ext .ts"
9fddcfc 対応しました。

2021-01-23 06:47 UTC, hgaiji commented on .travis.yml
> +      if: branch = master
5432e5b　対応しました。

2021-01-23 06:49 UTC, Yuki-TU approved these changes

2021-01-23 06:53 UTC, merged