header, footer, サイトイメージ部分
hgaiji/EDAR pull request #22
Opened 2021-01-30 04:57 UTC by hgaiji

## 実装内容
- Header.tsx
   - header部分を実装
- Footer.tsx
   - footer部分を実装
- EdarSiteContent.tsx
   - サイトイメージ部分を実装

### 全体の大枠部分について
- 全体の大枠部分についてはApp.tsxが担当しているので、実装はしていない
closed #21

2021-01-30 04:58 UTC, hgaiji commented
### 完成図
![image](https://user-images.githubusercontent.com/33284075/106347590-39c20380-6303-11eb-96aa-9345d9e97006.png)

2021-01-30 05:00 UTC, hgaiji commented
### 完成図(スマホサイズ)
![image](https://user-images.githubusercontent.com/33284075/106347614-7e4d9f00-6303-11eb-8c02-fdffcb89f489.png)

2021-02-02 19:40 UTC, Yuki-TU commented on src/edar/src/App.test.tsx
テストコードは各コンポーネントファイルごとに作成したほうがいい思います。
`Header.tsx`は一つのコンポーネントなので、それに対応する`Header.test.tsx'を`Header.tsx`と同フォルダ内に作る。
 
- 参考
  - 書き方
https://tech.zeals.co.jp/entry/2019/09/30/144410
  - 参考アプリのgithub
https://github.com/n05-frontend/shuwa-frontend-book-app/blob/chapter_6-6/src/Timeline.tsx

2021-02-03 11:05 UTC, Yuki-TU requested changes

2021-02-03 11:05 UTC, Yuki-TU commented on src/edar/src/components/Header.tsx
> +function GridMapping(props: any) {
下に書いたように型を指定してあげてください。


```

2021-02-03 11:05 UTC, Yuki-TU commented on src/edar/src/components/Header.tsx
> +export default function Header(props: any) {
`props: any`ではなく型定義はした方が良いと思います。他のanyもできるだけ、型定義をしてあげましょう。
やり方は2つあります。

- 方法1（間接定義）
```typescript
// 型定義（他のファイルでも型を使用するのであれば、exportをつける
// 今回の場合は多分他のところでは使わないのでexportは不要かと
// 他のところで使用する際はの読み取り方法↓
// import type {Props} from './Header.tsx'
export type Props = {
  title: string
  subtitle: string
}

export default function Header(props: Props) {
```

- 方法2（直接定義）
```typescript
export default function Header( props: { title: string, subtitle: string } ) {
```

2021-02-06 15:45 UTC, hgaiji commented on src/edar/src/components/Header.tsx
> +function GridMapping(props: any) {
11ae874 対応しました。
ただ、一部型定義できない部分があったので、anyとしています

2021-02-06 15:46 UTC, hgaiji commented on src/edar/src/App.test.tsx
5e82934　対応しました。

2021-02-06 18:43 UTC, Yuki-TU commented on src/edar/src/components/Header.test.tsx
> +    render(<Header title="Test" subtitle="testtest" />);
`Header`が定義されていないためテストが通りません。多分間違えて1行目で`Footer`をインポートしています。

2021-02-06 18:43 UTC, Yuki-TU commented on src/edar/src/App.tsx
> +      <EdarSiteContent />
ジャンルを選択し、レストランリスト表示するコンポーネント名を`MainContent`という名前にしているので、`EdarSiteContent`は`EdarSiteTop`とかの方が良いかもしれないです。

2021-02-07 02:43 UTC, hgaiji commented on src/edar/src/components/Header.test.tsx
> +    render(<Header title="Test" subtitle="testtest" />);
bde1853　ご指摘のとおりです。
修正しましたので、ご確認お願いします。

2021-02-07 02:46 UTC, hgaiji commented on src/edar/src/App.tsx
> +      <EdarSiteContent />
203bb7b 対応しました。

2021-02-07 11:58 UTC, Yuki-TU approved these changes

2021-02-09 10:13 UTC, Yuki-TU approved these changes

2021-02-09 10:16 UTC, Yuki-TU approved these changes

2021-02-09 12:29 UTC, merged