#32 ログイン機能の実装
hgaiji/EDAR pull request #39
Opened 2021-03-01 02:05 UTC by Yuki-TU

# 概要

closed #32
# 変更内容

- firebaseモジュールを導入
- Googleアカウントによる認証システムを採用しました。Googleアカウントがあれば認証をおこなうことができます。(今後はメール認証等増やす予定）
- ヘッダーメニューのアカウントを押すとダイアログが開き、「Googleによる認証はこちら」を押下すると、ポップアップが開き、Googleカウントでの認証を促す。認証が成功すると、成功しましたと、上部にダイアログが表示し、ヘッダーメニューのアイコンが自身のアカウントのアバター画像となる。
- ログオフは、ダイアログ上のログオフボタンを押下することで可能となっている。
- firebaseの認証関係は`src/edar/src/firebase/authentication.ts`にまとめてある。
- 予約、持ち帰り、配達、アカウントメニューは、それぞれのコンポーネントとしてファイル分割をした
- ログインユーザー情報は、名前とメールアドレスとアバター写真としており、今回はそれらをReduxで管理している。

- ログイン前
  - ダイアログ
![image](https://user-images.githubusercontent.com/51454617/109441651-22e50d00-7a79-11eb-9493-9fdb697d2e2c.png)
  - ヘッダー
![image](https://user-images.githubusercontent.com/51454617/109441667-355f4680-7a79-11eb-9b0c-68fae47ae779.png)

- ログイン時
  - ダイアログ
![image](https://user-images.githubusercontent.com/51454617/109441797-9ab33780-7a79-11eb-9872-dcfb2e865229.png)
  - ヘッダー
![image](https://user-images.githubusercontent.com/51454617/109441568-ea453380-7a78-11eb-9ce0-3bb32abd747c.png)

# 影響範囲

- Headerコンポーネント群、Footerコンポーネント群をそれぞれのディレクトリを作成し、その配下に置きました。
- Headerコンポーネントの関数名、変数名は、命名規則に従い書き直している個所がある。
- 
# 動作要件

- firebaseにログイン認証するために、firebaseのアクセスキーを必要とし、環境変数で置き換えております。

- 
# 補足

- `.env`に記載するfirebaseのアクセスキーは個別で送りますので、それを用いて動作確認お願いします。

2021-03-01 02:24 UTC, SHID4 commented
この量はプルリク分けた方が良さそう
見る側が気絶するかもしれん

2021-03-01 03:26 UTC, SHID4 requested changes

2021-03-01 03:26 UTC, SHID4 commented on src/edar/src/components/Header/Account.test.tsx
> +        render(<Account menuLabel={items[3].menuLabel} menuIcon={items[3].menuIcon} />);
マジックナンバーは定数化させるか
３が何なのかコメント付けるなりした方が良いね
(言語の使用わからんけど定数を宣言できるならそっちの方が良い）

特に配列の添字は後から見直したら何なのか分からんくなると思う

2021-03-01 03:26 UTC, SHID4 commented on src/edar/src/components/Header/Header.tsx
> +            </Grid>
ここら辺もっすね

2021-03-01 03:29 UTC, SHID4 commented
文字列なり数値なりベタがきしちゃうと拡張性が著しく下がっちゃうので、メソッド作る際には再利用性があるか部品化できそうかとか意識するとコードの綺麗度がマシマシチョモランマ⛰

2021-03-01 21:17 UTC, Yuki-TU commented
> 文字列なり数値なりベタがきしちゃうと拡張性が著しく下がっちゃうので、メソッド作る際には再利用性があるか部品化できそうかとか意識するとコードの綺麗度がマシマシチョモランマ⛰

確かに、全体を見てもメソッドコンポーネントそれぞれ汎用性が少ないですね。。（コンポーネント指向をあまり意識されていない）
調べたらコンポーネント指向の設計として、Atomic Designを意識した設計をしているところが多そう
これを採用するには、大幅に変更する必要がありそうなので、各ページごとでissue発行しておくちょもらんま⛰
- Atomic design参考
  - https://qiita.com/seya/items/8814e905693f00cdade2
  - https://zenn.dev/camcam_lemon/articles/1f518d6831e2a5be4524
  - https://blog.spacemarket.com/code/atomic-design%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6react%E3%82%B3%E3%83%B3%E3%83%9D%E3%83%BC%E3%83%8D%E3%83%B3%E3%83%88%E3%82%92%E5%86%8D%E8%A8%AD%E8%A8%88%E3%81%97%E3%81%9F%E8%A9%B1/

2021-03-01 21:19 UTC, Yuki-TU commented on src/edar/src/components/Header/Header.tsx
> +            </Grid>
対応済み
https://github.com/hgaiji/EDAR/pull/39/commits/9ca750cc5a78602f8d4a01009b0c2c345ded9bd3

2021-03-01 21:20 UTC, Yuki-TU commented on src/edar/src/components/Header/Account.test.tsx
> +        render(<Account menuLabel={items[3].menuLabel} menuIcon={items[3].menuIcon} />);
対応済み
https://github.com/hgaiji/EDAR/pull/39/commits/9ca750cc5a78602f8d4a01009b0c2c345ded9bd3

2021-03-02 13:28 UTC, hgaiji commented on src/edar/.env.example
> +REACT_APP_MEASUREMENT_ID=[_MEASUREMENT_ID]
こちらなのですが、以前設定したような形で、__HOGEHOGE__という形で統一してほしいです。
例)
```
REACT_APP_API_KEY=__APP_API_KEY__
```

2021-03-02 13:44 UTC, hgaiji commented on src/edar/src/components/Header/Account.test.tsx
> +
同じ名前だとまずくないですか？

2021-03-02 13:48 UTC, hgaiji commented on src/edar/src/components/Header/TakeOut.test.tsx
> +    });
こちらもマジックナンバーになってますね。

2021-03-02 13:48 UTC, hgaiji commented on src/edar/src/components/Header/Reservation.test.tsx
> +    });
こちらもマジックナンバーになってますね。

2021-03-02 14:09 UTC, hgaiji commented on src/edar/src/components/Header/Account.test.tsx
> +        render(<Account menuLabel={items[3].menuLabel} menuIcon={items[3].menuIcon} />);
対応できていないようです。
`src/edar/src/components/Header/Account.test.tsx`

2021-03-03 22:09 UTC, Yuki-TU commented on src/edar/src/components/Header/Account.test.tsx
> +
https://qiita.com/r_1105/items/3444f957bcfa9811c250
を参考に、作成したのですが、あまりよくわかってません。。
この参考資料の中では、`const useSelectorMock = useSelector as jest.Mock<number>;`となっているのですが、これはRedux上で扱う値がnumberだから、こう設定していると解釈しました。今回は、様々値を扱うため、特に指定せずに使用している状態です。

2021-03-03 22:11 UTC, Yuki-TU commented on src/edar/src/components/Header/Account.test.tsx
> +        render(<Account menuLabel={items[3].menuLabel} menuIcon={items[3].menuIcon} />);
テストコードは見落としてた。。。
対応済み
https://github.com/hgaiji/EDAR/pull/39/commits/1552928f611ae7028eec1d9aba06c219b9704982

2021-03-03 22:12 UTC, Yuki-TU commented on src/edar/.env.example
> +REACT_APP_MEASUREMENT_ID=[_MEASUREMENT_ID]
対応済み
https://github.com/hgaiji/EDAR/pull/39/commits/58ce09bbf93763323034330761f0b433552825c0

2021-03-03 22:13 UTC, Yuki-TU commented on src/edar/src/components/Header/Reservation.test.tsx
> +    });
対応済み
https://github.com/hgaiji/EDAR/pull/39/commits/1552928f611ae7028eec1d9aba06c219b9704982

2021-03-03 22:13 UTC, Yuki-TU commented on src/edar/src/components/Header/TakeOut.test.tsx
> +    });
対応済み
https://github.com/hgaiji/EDAR/pull/39/commits/1552928f611ae7028eec1d9aba06c219b9704982

2021-03-04 05:41 UTC, hgaiji commented on src/edar/.env.example
> +REACT_APP_MEASUREMENT_ID=[_MEASUREMENT_ID]
上記にも記載しましたが、以下の対応ないおうだと何を表した環境変数かよくわからないので、
```
EACT_APP_API_KEY=__FIREBASE_API_KEY__
REACT_APP_AUTH_DOMAIN=__FIREBASE_AUTH_DOMAIN__
REACT_APP_PROJECT_ID=__FIREBASE_PROJECT_ID__
REACT_APP_STORAGE_BUCKET=__FIREBASE_STORAGE_BUCKET__
REACT_APP_MESSAGING_SENDER_ID=__FIREBASE_MESSAGING_SENDER_ID__
REACT_APP_APP_ID=__FIREBASE_APP_ID__
REACT_APP_MEASUREMENT_ID=__FIREBASE_MEASUREMENT_ID__
```

のように対応していただいてよいでしょうか。

2021-03-05 11:33 UTC, Yuki-TU commented on src/edar/.env.example
> +REACT_APP_MEASUREMENT_ID=[_MEASUREMENT_ID]
ごめんー見落としてた。。。。
対応済み
https://github.com/hgaiji/EDAR/pull/39/commits/b86c87cf8f2960e38cbb609e744d526a393d40a7

2021-03-06 05:00 UTC, hgaiji commented
LGTM

2021-03-06 05:00 UTC, hgaiji approved these changes

2021-03-06 05:02 UTC, SHID4 approved these changes

2021-03-06 05:07 UTC, merged

2021-03-06 05:09 UTC, hgaiji commented on src/edar/.env.example
> +REACT_APP_MESSAGING_SENDER_ID=__FIREBASE_MESSAGING_SENDER_ID__
REACT_APP_STORAGE_BUCKET=__FIREBASE_STORAGE_BUCKET__
REACT_APP_MESSAGING_SENDER_ID=__FIREBASE_MESSAGING_SENDER_ID__

はfirebaseの認証に使用しないので、不要じゃないかな？

2021-03-06 05:12 UTC, hgaiji commented on src/edar/.env.example
> +REACT_APP_MESSAGING_SENDER_ID=__FIREBASE_MESSAGING_SENDER_ID__
不要の場合は、別PRで対応予定